version: '3.8'

services:
   botapeer_core:
      build:
         context: .
      ports:
      - 8081:8080
      volumes:
      - .:/app
      - "${HOME}/.m2:/root/.m2"
      tty: true
      depends_on:
      - db
      environment:
       - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
       - DB_USERNAME=${DB_USERNAME}
       - DB_PASSWORD=${DB_PASSWORD}
       - DB_DRIVER_CLASS_NAME=${DB_DRIVER_CLASS_NAME}
       - S3_ACCESS_KEY=${S3_ACCESS_KEY}
       - S3_SECRET_KEY=${S3_SECRET_KEY}
       - AWS_REGION_STATIC=${AWS_REGION_STATIC}
       - JWT_SECRET=${JWT_SECRET}
       - JWT_EXPIRATION_IN_MS=${JWT_EXPIRATION_IN_MS}
       - IMAGE_PATH=${IMAGE_PATH}
   botapeer_core_debug:
      build:
         context: .
         dockerfile: Dockerfile.debug
      ports:
      - 8081:8080
      - 5005:5005
      volumes:
      - .:/app
      - "${HOME}/.m2:/root/.m2"
      tty: true
      depends_on:
      - db
      environment:
       - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
       - DB_USERNAME=${DB_USERNAME}
       - DB_PASSWORD=${DB_PASSWORD}
       - DB_DRIVER_CLASS_NAME=${DB_DRIVER_CLASS_NAME}
       - S3_ACCESS_KEY=${S3_ACCESS_KEY}
       - S3_SECRET_KEY=${S3_SECRET_KEY}
       - AWS_REGION_STATIC=${AWS_REGION_STATIC}
       - JWT_SECRET=${JWT_SECRET}
       - JWT_EXPIRATION_IN_MS=${JWT_EXPIRATION_IN_MS}
       - IMAGE_PATH=${IMAGE_PATH}       
   db:
      image: mysql:8.0.31
      ports:
      - 33061:3306
      environment:
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
         MYSQL_DATABASE: ${DB_SCHEMA}
