version: '3.8'

services:
   ryokujun_core:
      build:
         context: .
      ports:
      - 8081:8080
      volumes:
      - .:/app
      tty: true
      depends_on:
      - db
      environment:
       - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
       - DB_USERNAME=${DB_USERNAME}
       - DB_PASSWORD=${DB_PASSWORD}
       - DB_DRIVER_CLASS_NAME=${DB_DRIVER_CLASS_NAME}
   migrate:
      image: flyway/flyway
      command: -url=${DB_URL} -schemas=${DB_SCHEMA} -user=${DB_USERNAME} -password=${DB_PASSWORD} migrate
      depends_on:
         db:
            condition: service_healthy
   db:
      image: mysql:8.0.31
      ports:
      - 33061:3306
      environment:
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
         MYSQL_DATABASE: ${DB_SCHEMA}
      healthcheck:
         test: mysqladmin ping -h 127.0.0.1 -u${DB_USERNAME} -p${DB_PASSWORD}
