version: '3.8'

services:
   botapeer_core_test:
      build:
         context: .
      ports:
      - 8081:8080
      volumes:
      - .:/app
      - "${HOME}/.m2:/root/.m2"
      tty: true
      depends_on:
      - db_test
      environment:
       - SPRING_DATASOURCE_URL=jdbc:mysql://db_test/${DB_SCHEMA}
       - DB_USERNAME=${DB_USERNAME}
       - DB_PASSWORD=${DB_PASSWORD}
       - DB_DRIVER_CLASS_NAME=${DB_DRIVER_CLASS_NAME}
       - S3_ACCESS_KEY=${S3_ACCESS_KEY}
       - S3_SECRET_KEY=${S3_SECRET_KEY}
       - AWS_REGION_STATIC=${AWS_REGION_STATIC}
       - JWT_SECRET=${JWT_SECRET}
       - JWT_EXPIRATION_IN_MS=${JWT_EXPIRATION_IN_MS}
       - IMAGE_PATH=${IMAGE_PATH}
   db_test:
     image: mysql:8.0.31
     ports:
       - 33062:3306
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
       MYSQL_DATABASE: ${DB_SCHEMA}
