FROM eclipse-temurin:11-jdk-focal
RUN apt-get update  \
 && apt-get install maven -y \
 && apt-get install -y vim
WORKDIR /app
COPY . /app
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"]