BEGIN;
ALTER TABLE likes DROP FOREIGN KEY likes_ibfk_1;
ALTER TABLE likes DROP FOREIGN KEY likes_ibfk_2;
ALTER TABLE likes DROP FOREIGN KEY likes_ibfk_3;

ALTER TABLE likes ADD CONSTRAINT FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE likes ADD CONSTRAINT FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE likes ADD CONSTRAINT FOREIGN KEY (comment_id) REFERENCES comments (id) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;